package main.interpreter.values.builtins;

import main.interpreter.values.InvalidOperationException;

import java.util.Iterator;
import java.util.List;

public sealed abstract class Value implements Iterable<Value>, Iterator<Value>
        permits
        // function generated by a declaration
        InterpretedFunctionValue,
        // class generated by a declaration
        InterpretedClassValue,
        // function generated by operators (f + g) or similar (eg native methods on primitives like list.append)
        CompiledFunctionValue,
        // numbers
        NumericValue,
        // strings
        StringValue,
        // objects
        ObjectValue,
        // lists
        ListValue,
        // vectors
        VectorValue,
        // booleans
        BooleanValue,
        // null
        NullValue,
        // enums
        EnumValue,
        // enum handles
        EnumHandleValue,
        // ranges
        RangeValue,
        // maps
        DictionaryValue,
        // hash sets
        SetValue,
        // builtins eg files
        BuiltinObjectValue,
        // big numbers (special case)
        BigNumberValue
{
    public abstract Value add(Value other);
    public abstract Value sub(Value other);
    public abstract Value mul(Value other);
    public abstract Value div(Value other);
    public abstract Value mod(Value other);
    public abstract Value getMember(String name);
    public abstract Value index(Value index);
    public abstract Value call(List<Value> args);
    public abstract BooleanValue eq(Value other);
    public abstract Value neg();
    public abstract Value inv();
    public abstract BooleanValue isTruthy();
    public abstract BooleanValue neq(Value other);
    public abstract BooleanValue lt(Value other);
    public abstract BooleanValue lte(Value other);
    public abstract BooleanValue gt(Value other);
    public abstract BooleanValue gte(Value other);
    public abstract Value toNumber();
    public abstract String toString();
    public abstract Value setMember(String name, Value value);
    public abstract Value setIndex(Value index, Value value);
    public abstract Value merge(Value v);
    public BooleanValue contains(Value v) {
        throw new InvalidOperationException("Cannot use 'in' operator on this value");
    }
    public boolean equals(Object other) {
        return other instanceof Value v && eq(v).value;
    }
    public Value last() {
        throw new InvalidOperationException("Cannot get last element of a value");
    }
    public Value first() {
        throw new InvalidOperationException("Cannot get first element of a value");
    }

    @Override
    public Iterator<Value> iterator() {
        throw new InvalidOperationException("Iterators are not supported on this data type");
    }
    public Value next() {
        throw new InvalidOperationException("This type is not an iterator");
    }
    public boolean hasNext() {
        throw new InvalidOperationException("This type is not an iterator)");
    }
    public Value length() {
        throw new InvalidOperationException("Cannot get length of this value");
    }
}
