package main.interpreter.values;

import java.util.List;

public sealed abstract class Value permits
        // function generated by a declaration
        InterpretedFunctionValue,
        // class generated by a declaration
        InterpretedClassValue,
        // function generated by operators (f + g) or similar (eg native methods on primitives like list.append)
        CompiledFunctionValue,
        // numbers
        NumericValue,
        // strings
        StringValue,
        // objects
        ObjectValue,
        // lists
        ListValue,
        // vectors
        VectorValue,
        // booleans
        BooleanValue,
        // null
        NullValue
{
    public abstract Value add(Value other);
    public abstract Value sub(Value other);
    public abstract Value mul(Value other);
    public abstract Value div(Value other);
    public abstract Value mod(Value other);
    public abstract Value getMember(String name);
    public abstract Value index(Value index);
    public abstract Value call(List<Value> args);
    public abstract BooleanValue eq(Value other);
    public abstract Value neg();
    public abstract Value inv();
    public abstract BooleanValue isTruthy();
    public abstract BooleanValue neq(Value other);
    public abstract BooleanValue lt(Value other);
    public abstract BooleanValue lte(Value other);
    public abstract BooleanValue gt(Value other);
    public abstract BooleanValue gte(Value other);
    public abstract Value toNumber();
    public abstract String toString();
    public abstract Value setMember(String name, Value value);
    public abstract Value setIndex(Value index, Value value);
    public abstract Value merge(Value v);
}
